config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  get "home", to: "pages#home"

  #creating dashboard
  get "dashboard", to: "lessons#dashboard"


  get "design", to: "pages#design"
  root 'pages#home'
  resources :lessons  do
    resources :bookings, only: [:create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :lesson
  belongs_to :user


# needs: status exists - inclusion (pending/confirmed/rejected)
      #  booking_time - exists, only integer true
  validate :date_is_in_the_future
  validates :lesson, presence: true
  validates :user, presence: true
  validates :status, presence: true, inclusion: {in: %w(pending accepted declined)}
  validates :booking_time, presence: true

  def date_is_in_the_future
    if booking_time.present? && booking_time < Time.now
      errors.add(:booking_time, "Can't be in the past")
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  belongs_to :user

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  validates :description, presence: true, length: {minimum: 15}
  validates :location, presence: true
  validates :category, presence: true, inclusion: {in: %w(coding arts school)}
  validates :price, presence: true, numericality: { only_integer: true }
  validates :title, presence: true
  validates :user, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  class Product < ApplicationRecord
    has_attachment :photo
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lessons
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_lesson, only: [:create, :update]

  def create
    @booking = Booking.new(booking_params)
    @booking.lesson = @lesson
    @booking.user = current_user
    @booking.status = 'pending'
    @booking.save
    redirect_to lesson_path(@lesson)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to lesson_path(@lesson)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to lesson_path(@lesson)
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def booking_params
    params.require(:booking).permit(:booking_time, :status)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  def index
    @lessons = Lesson.where.not(latitude: nil, longitude: nil)
    if params[:category]
      @category = params[:category]
      @lessons = @lessons.where(category: @category)
    end

    @hash = Gmaps4rails.build_markers(@lessons) do |lesson, marker|
      marker.lat lesson.latitude
      marker.lng lesson.longitude
    end
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.user = current_user
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @lesson = Lesson.find(params[:id])
    @lesson_coordinates = { lat: @lesson.latitude, lng: @lesson.longitude }
    @alert_message = "Your booking was successful. Go to my dashboard to view all your bookings."
  end

  def edit
  end

  def update
    @lesson.update(lesson_params)
  end

  def destroy
    @lesson.destroy
  end

  #creating dashboard logic
  def dashboard
    #accedpted lessons

    @lessons = current_user.lessons
    @accepted_bookings = current_user.bookings.select {|b| b.status == 'accepted' }
    @pending_bookings = current_user.bookings.select {|b| b.status == 'pending' }
    @declined_bookings = current_user.bookings.select {|b| b.status == 'declined' }
    #@accepted_bookings = Booking.joins(:lesson).where(lessons: {user: current_user}, status: "accepted")
    #@pending_bookings = Booking.joins(:lesson).where(lessons: {user: current_user}, status: "pending")
    #@declined_bookings = Booking.joins(:lesson).where(lessons: {user: current_user}, status: "declined")

    @lessons = current_user.lessons
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:description, :location, :category, :price, :title, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def design
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def product_params
    params.require(:product).permit(:name, :description, :photo)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/_footer.html.erb
<div class="footer hidden-xs">
  <div class="footer-links col-xs-4 col-md-12">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright col-xs-4 col-md-12">
    This footer is made with <i class="fa fa-heart"></i> by Nick, Hakeem and Ashlee
  </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- NAVBAR -->



<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png", {id: "logo"}%>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <%= link_to "Create Lesson", new_lesson_path, class: "navbar-wagon-item btn btn-primary btn-teachpin" %>

    <% if !current_user %>
    <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-btn" %>
    <a href="/users/sign_up" class="navbar-wagon-item navbar-btn">Sign up</a>
    <% end %>


    <!-- Profile picture with dropdown list -->
    <% if current_user %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/nickvang" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "My Dashboard", dashboard_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: 'delete' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/lessons/new">Create Lesson</a></li>
        <li><%= link_to "My Dashboard", dashboard_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: 'delete' %></li>
      </ul>
    </div>
  </div>
</div>



</body>
</html>

app/views/layouts/_tab.html.erb
<div class="tabs">
  <%= link_to dashboard_path(active: "accepted"), class: 'tab active' do  %>
  <h3>Lessons</h3>
  <p>Accepted</p>

  <% end %>
  <%= link_to dashboard_path(active: "pending"), class: 'tab' do  %>
  <h3>Lessons</h3>
  <p>Pending</p>
  <% end %>
  <%= link_to dashboard_path(active: "declined"), class: 'tab' do %>
  <h3>Lessons</h3>
  <p>Declined</p>
  <% end %>

  <div class="container">
    <div class="row">
      <% @filtered_bookings.each do  |booking| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= bg_path %>');">
          <div class="card-category"><%= booking.lesson.title %></div>
          <div class="card-description">
            <p><%= booking.booking_time %></p>
            <p><%= booking.status %></p>
          </div>
          <div class="card-price">
            <p><%="DKK #{booking.lesson.price}" %></p>
          </div>
          <div class="card-user">

          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>


  <div class="container">
    <div class="row">
      <% @lessons.each do  |lesson| %>
      <div class="col-xs-12 col-sm-4">
        <% if lesson.category == "school" %>
        <% bg_path = image_path 'school.png' %>
        <% elsif lesson.category == "coding" %>
        <% bg_path = image_path 'coding.png' %>
        <% elsif lesson.category == "arts" %>
        <% bg_path = image_path 'arts.png'  %>
        <% end %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= bg_path %>');">
          <%= link_to lesson_path(lesson) do %>
          <div class="card-category"><%= lesson.title %></div>
          <div class="card-description">
            <p><%= lesson.location %></p>
            <p><%= lesson.category %></p>
          </div>
          <div class="card-price">
            <p><%="DKK #{lesson.price}" %></p>
          </div>
          <div class="card-user">

          </div>

        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TeachPin</title>


  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="teach-pin-container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key= #{ENV['GOOGLE_API_SERVER_KEY']}"%>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>



  <%= yield(:after_js) %>
  <%= cloudinary_js_config %>
</body>
</html>

app/views/lessons/_bookings_column.html.erb
    <div class="cell">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= bg_path %>');">
        <div class="card-category"><%= booking.lesson.title %></div>
        <div class="card-description">
          <p><%= booking.lesson.location %></p>
          <p><%= booking.lesson.category.capitalize %></p>
          <p id="card-status"><%= booking.status.capitalize %></p>
        </div>
        <div class="card-price">
          <p><%="DKK #{booking.lesson.price}" %></p>
        </div>
      </div>
    </div>

app/views/lessons/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for (@lesson)  do |f| %>
  <p>Select a Category</p>
    <%= f.select :category, category: %w(arts coding school)%>
    <%= f.input :title, label: "Title of your lesson" %>
    <%= f.input :location, :label => "Select a Location" %>
    <%= f.input :description, as: :text, :label => "Describe the lesson" %>
    <%= f.input :price, :label => "Price" %>
    <%= f.submit 'Create', class: "btn btn-success" %>
  <% end %>
</div>

app/views/lessons/create.html.erb
<!-- NO DATA IN THIS FILE -->

app/views/lessons/dashboard.html.erb
  <div id="image-banner" class="booking-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "dashboard_banner.png" %>');">
  <div class="banner-content">
    <h1>My Dashboard</h1>
    <p>View all your classes and lessons</p>
  </div>
</div>

<div class="dashboard-wrapper">
  <div class="booking_columns">

    <div class="accepted-column">
      <% @accepted_bookings.each do |booking| %>
        <% if booking.lesson.category == "school" %>
          <% bg_path = image_path 'school.png' %>
        <% elsif booking.lesson.category == "coding" %>
          <% bg_path = image_path 'coding.png' %>
        <% elsif booking.lesson.category == "arts" %>
          <% bg_path = image_path 'arts.png'  %>
        <% end %>
      <%= render partial: 'bookings_column', locals:{booking: booking, bg_path: bg_path} %>
      <% end %>
    </div>


    <div class="pending-column">
      <% @pending_bookings.each do |booking| %>
        <% if booking.lesson.category == "school" %>
            <% bg_path = image_path 'school.png' %>
        <% elsif booking.lesson.category == "coding" %>
           <% bg_path = image_path 'coding.png' %>
        <% elsif booking.lesson.category == "arts" %>
           <% bg_path = image_path 'arts.png'  %>
        <% end %>
      <%= render partial: 'bookings_column', locals:{booking: booking, bg_path: bg_path} %>
      <% end %>
    </div>


    <div class="declined-column">
      <% @declined_bookings.each do |booking| %>
        <% if booking.lesson.category == "school" %>
            <% bg_path = image_path 'school.png' %>
        <% elsif booking.lesson.category == "coding" %>
            <% bg_path = image_path 'coding.png' %>
        <% elsif booking.lesson.category == "arts" %>
            <% bg_path = image_path 'arts.png'  %>
        <% end %>
      <%= render partial: 'bookings_column', locals:{booking: booking, bg_path: bg_path} %>
      <% end %>
    </div>
  </div>
</div>

app/views/lessons/destroy.html.erb
<h1>Lessons#destroy</h1>
<p>Find me in app/views/lessons/destroy.html.erb</p>

app/views/lessons/edit.html.erb
<%= render 'form' %>

app/views/lessons/index.html.erb
<div class="index-container">
  <div class="card-container">
    <div class="row">
      <% @lessons.each do  |lesson| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <% if lesson.category == "school" %>
        <% bg_path = image_path 'school.png' %>
        <% elsif lesson.category == "coding" %>
        <% bg_path = image_path 'coding.png' %>
        <% elsif lesson.category == "arts" %>
        <% bg_path = image_path 'arts.png' %>
        <% end %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= bg_path %>');">
          <%= link_to lesson_path(lesson) do %>
          <div class="card-category col-xs-4 col-md-12"><%= lesson.title %></div>
          <div class="card-description">
            <p><%= lesson.location %></p>
            <p><%= lesson.category %></p>
          </div>
          <div class="card-price">
            <p><%="DKK #{lesson.price}" %></p>
          </div>
          <div class="card-user">
            <% if lesson.category == "school" %>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/<%= %w[mobajo  jeremyboom8 hmatringe].sample %>">
            <% elsif lesson.category == "coding" %>
            <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/<%= %w[atmosfeer ashleeste keemtaker ].sample %>">
            <% elsif lesson.category == "arts" %>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/<%= %w[ssaunier bobbymitchell].sample %>">
          <% end %>
          </div>
          <a class="card-link" href="<%= lesson_path(lesson) %>" ></a>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div id="map" class="hidden-xs" style= "height: 100vh; width: 400px;"></div>
</div>

<% content_for(:after_js) do %>
<script type="text/javascript">
  var handler = Gmaps.build('Google');
  handler.buildMap({ internal: { id: 'map' } }, function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(14);
    }
  });
</script>
<% end %>

app/views/lessons/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'teach1.png'%>)">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8">
       <!-- <div class="page-content"> -->
        <div class="banner-content">
          <h1>Become a Teacher</h1>
          <p>Share your passion</p>
      </div>
        <!-- </div> -->
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="form-container">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>
  </div>

app/views/lessons/show.html.erb
<div class="booking-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "book.png" %>');">
  <div class="banner-content">
    <h1>Book a <%= @lesson.category %> lesson</h1>
    <p>Easy and Simple Lessons from a Professional</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <!-- <div class="form-wrapper"> -->
       <div class="icons">
        <i class="fa fa-graduation-cap" aria-hidden="true"> Professional Teachers</i>  <i class="fa fa-book" aria-hidden="true"> Advanced Lessons </i>  <i class="fa fa-calendar-check-o" aria-hidden="true"> Your Schedule</i>  <i class="fa fa-map-marker" aria-hidden="true"> Conviently Located</i>
      </div>

      <div class="lesson-description">
        <div class="lesson-booking-card-category">
          <h3><%= @lesson.title %></h2>
        </div>
          <div class="lesson-booking-card-description">
            <!-- <div class="info-form"> -->
              <%= @lesson.description %>
            </div>
            <div class='lesson-booking-card-price'>
              <p><%= "DKK #{@lesson.price} per hour" %></p>
            </div>
      </div>
    </div>
          <!-- </div> -->
          <div class="col-xs-12 col-md-4">
            <!-- <div class="booking-form"> -->
              <div class="form-wrapper input-text">
                <%= simple_form_for([@lesson, @booking])  do |f| %>
                <div class="form-title">
                  <%= f.input :booking_time, label: "Select A Lesson Time" %>
                </div>
                <div id="book" class="form-button">

                  <%= f.submit 'Book Now', class: "btn btn-danger booking-btn", :onclick => 'alert("Booking Successful! View all bookings in my dashboard")' %>
                  <% end %>
                </div>
              </div>
          </div>
    </div>
  </div>
</div>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>

app/views/pages/_banner.html.erb
<!-- BANNER -->
<div class="container">
    <div id="banner">
      <h2>Banner</h2>
      <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://picsum.photos/200/300/?random');">
        <div class="banner-content">
          <h1>Welcome to TeachPin</h1>
          <p>Easy and Simple teaching from professionals</p>
          <ul>
            <a class='btn btn-primary btn-category' href='#' >Music</a>
            <a class='btn btn-primary btn-category' href='#' >Coding</a>
            <a class='btn btn-primary btn-category' href='#' >School</a>
            <a class='btn btn-primary btn-category' href='#' >Craft</a>
            <a class='btn btn-primary btn-category' href='#' >Arts</a>
          </ul>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/_button.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>



  <h1>Design Page</h1>
  <h2>Buttons</h2>
  <div>
    <ul>
      <a class='btn btn-primary btn-teachpin' href='#' >Login</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Sign up</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Create</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Book</a>
      <a class='btn btn-primary btn-category' href='#' >Category</a>

    </ul>
  </div>



</body>
</html>

app/views/pages/_design.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>



  <h1>Design Page</h1>
  <h2>Buttons</h2>
  <div>
    <ul>
      <a class='btn btn-primary btn-teachpin' href='#' >Login</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Sign up</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Create</a>
      <a class='btn btn-primary btn-teachpin' href='#' >Book</a>
      <a class='btn btn-primary btn-category' href='#' >Category</a>

    </ul>
  </div>



</body>
</html>

app/views/pages/_home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/_navbar.html.erb
<!-- NAVBAR -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <div class="navbar-wagon">
    <!-- Logo -->
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "logo.png", {id: "logo"}%>
    </a>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <a href="" class="navbar-wagon-item btn btn-primary btn-teachpin">Create Lesson</a>
      <a href="" class="navbar-wagon-item btn btn-primary btn-teachpin">Login</a>
      <a href="" class="navbar-wagon-item btn btn-primary btn-teachpin">Sign up</a>


      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">My Lessons</a></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </div>
      </div>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Create Lesson</a></li>
        </ul>
      </div>
    </div>
  </div>

</body>
</html>

app/views/pages/banner.html.erb
<!-- BANNER -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
<div class="container">
    <div id="banner">
      <h2>Banner</h2>
      <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://picsum.photos/200/300/?random');">
        <div class="banner-content">
          <h1>Welcome to TeachPin</h1>
          <p>Easy and Simple teaching from professionals</p>


          <ul>
            <a class='btn btn-primary btn-category' href='#' >Music</a>
            <a class='btn btn-primary btn-category' href='#' >Coding</a>
            <a class='btn btn-primary btn-category' href='#' >School</a>
            <a class='btn btn-primary btn-category' href='#' >Craft</a>
            <a class='btn btn-primary btn-category' href='#' >Arts</a>
          </ul>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/pages/create.html.erb
<!-- BANNER -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>


  <!-- BANNER -->

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path 'teach1.png'%>)">
    <div class="main-container">

      <h1 class="text-center main-container">Become a Teacher</h1>
      <p class="text-center main-container">Share your passion</p>
    </div>

  </div>
</body>
</html>